---
- name: My Test Playbook
  hosts: all
  become: yes

  tasks:
  - name: Installing httpd
    yum:
      name: httpd
      state: present
    notify: Starting httpd

  handlers:
  - name: Starting httpd
    service:
      name: httpd
      state: started

