---
- name: Installing httpd
  yum:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"
  notify: Starting httpd

- name: Installing apache2
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"
  notify: Starting apache2

- name: Copy index.html
  copy:
    src: /home/ansadmin/index.html
    dest: /var/www/html

